version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: webpack
    versions:
    - 4.46.0
    - 5.21.0
    - 5.21.2
    - 5.23.0
    - 5.24.2
    - 5.24.3
    - 5.25.0
    - 5.27.0
    - 5.28.0
    - 5.30.0
    - 5.31.2
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.4
    - 1.3.5
    - 1.3.6
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: postcss
    versions:
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: react-dropzone
    versions:
    - 11.2.4
    - 11.3.1
  - dependency-name: postcss-loader
    versions:
    - 4.2.0
  - dependency-name: ini
    versions:
    - 1.3.8
